# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(530, 266)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-image: url(:/Img/bg.jpg);")
        MainWindow.setIconSize(QtCore.QSize(18, 18))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 530, 18))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuMongoDB = QtWidgets.QMenu(self.menubar)
        self.menuMongoDB.setObjectName("menuMongoDB")
        self.menuVisualization = QtWidgets.QMenu(self.menubar)
        self.menuVisualization.setObjectName("menuVisualization")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionInsert = QtWidgets.QAction(MainWindow)
        self.actionInsert.setObjectName("actionInsert")
        self.actionRetrieve = QtWidgets.QAction(MainWindow)
        self.actionRetrieve.setObjectName("actionRetrieve")
        self.actionUpdate = QtWidgets.QAction(MainWindow)
        self.actionUpdate.setObjectName("actionUpdate")
        self.actionDelete = QtWidgets.QAction(MainWindow)
        self.actionDelete.setObjectName("actionDelete")
        self.actionBox_Plot = QtWidgets.QAction(MainWindow)
        self.actionBox_Plot.setObjectName("actionBox_Plot")
        self.actionScatter_Plot = QtWidgets.QAction(MainWindow)
        self.actionScatter_Plot.setObjectName("actionScatter_Plot")
        self.actionHistogram = QtWidgets.QAction(MainWindow)
        self.actionHistogram.setObjectName("actionHistogram")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionExit)
        self.menuMongoDB.addAction(self.actionInsert)
        self.menuMongoDB.addAction(self.actionRetrieve)
        self.menuMongoDB.addAction(self.actionUpdate)
        self.menuMongoDB.addAction(self.actionDelete)
        self.menuVisualization.addAction(self.actionBox_Plot)
        self.menuVisualization.addAction(self.actionScatter_Plot)
        self.menuVisualization.addAction(self.actionHistogram)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuMongoDB.menuAction())
        self.menubar.addAction(self.menuVisualization.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MineMax"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuMongoDB.setTitle(_translate("MainWindow", "Storage"))
        self.menuVisualization.setTitle(_translate("MainWindow", "Visualization"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionInsert.setText(_translate("MainWindow", "Insert File"))
        self.actionRetrieve.setText(_translate("MainWindow", "Retrieve File"))
        self.actionUpdate.setText(_translate("MainWindow", "Update File"))
        self.actionDelete.setText(_translate("MainWindow", "Delete File"))
        self.actionBox_Plot.setText(_translate("MainWindow", "Box Plot"))
        self.actionScatter_Plot.setText(_translate("MainWindow", "Scatter Plot"))
        self.actionHistogram.setText(_translate("MainWindow", "Histogram"))


